imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
cygnus_olytics:
    connection:
        server: 'mongodb://10.0.2.101:27017,10.0.2.102:27017,10.0.2.103:27017'
        options:
            readPreference: nearest
            replicaSet: analytics
            journal: false
            w: 1
            connectTimeoutMS: 200
